version: '3.8'

   services:
     app:
       build:
         context: .
         dockerfile: Dockerfile
       ports:
         - "8080:8080"
       volumes:
         - ./logs:/usr/local/tomcat/logs
       environment:
         - JAVA_OPTS